"""PACT configuration generator — converts extracted assessment data to PACT YAML.

Targets OrgGeneratorConfig format, which can be imported into pact-platform's
OrgGenerator for automatic envelope derivation with monotonic tightening.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

import yaml

from care.conversation.session import ExtractedData


_TRUST_POSTURE_MAP = {
    "minimal": "pseudo",
    "closely supervised": "supervised",
    "supervised": "supervised",
    "collaborative": "shared_planning",
    "mostly independent": "continuous_insight",
    "fully autonomous": "delegated",
    None: "supervised",  # default
}

_DEFAULT_ROLES = [
    "executive_assistant",
    "data_analyst",
    "content_writer",
    "customer_support",
    "scheduler",
    "researcher",
]


@dataclass
class PactConfigResult:
    yaml_content: str
    config_dict: dict[str, Any]
    summary: str


def generate_pact_config(extracted: ExtractedData) -> PactConfigResult:
    """Generate PACT-compatible YAML from assessment data."""
    config = _build_config(extracted)
    yaml_content = yaml.dump(
        config, default_flow_style=False, sort_keys=False, allow_unicode=True
    )
    summary = _build_summary(extracted, config)

    return PactConfigResult(
        yaml_content=yaml_content,
        config_dict=config,
        summary=summary,
    )


def _build_config(extracted: ExtractedData) -> dict[str, Any]:
    """Build the PACT OrgGeneratorConfig-compatible structure."""
    org_name = extracted.org_name or "My Organization"
    posture = _map_trust_posture(extracted.target_trust_posture)

    config: dict[str, Any] = {
        "_comment": (
            f"Generated by CARE Assessment Kit on "
            f"{datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
        ),
        "_care_version": "0.1.0",
        "organization": {
            "name": org_name,
            "initial_posture": posture,
        },
        "genesis": {
            "authority": f"{_slugify(org_name)}-root",
            "authority_name": f"{org_name} Governance Authority",
            "policy_reference": f"CARE Assessment — {org_name}",
        },
    }

    # Departments and teams
    departments = _build_departments(extracted)
    if departments:
        config["departments"] = departments

    # Constraint envelopes
    envelope = _build_root_envelope(extracted)
    config["root_envelope"] = envelope

    # Bridges
    if extracted.bridges:
        config["bridges"] = _build_bridges(extracted)

    # Gaps (informational — not part of PACT config, but useful for the recipient)
    if extracted.gaps:
        config["_assessment_gaps"] = [
            g if isinstance(g, str) else g.get("description", str(g))
            for g in extracted.gaps
        ]

    return config


def _build_departments(extracted: ExtractedData) -> list[dict[str, Any]]:
    """Build department definitions from extracted data."""
    departments: list[dict[str, Any]] = []

    if extracted.departments:
        for dept in extracted.departments:
            dept_def: dict[str, Any] = {
                "name": dept.get("name", "Unknown Department"),
            }

            # Find teams belonging to this department
            dept_teams = [
                t
                for t in extracted.teams
                if t.get("department", "").lower() == dept.get("name", "").lower()
            ]

            if dept_teams:
                dept_def["teams"] = [
                    {
                        "name": t.get("name", "Unknown Team"),
                        "roles": _infer_roles(t),
                    }
                    for t in dept_teams
                ]
            else:
                # Default team with default roles
                dept_def["teams"] = [
                    {
                        "name": f"{dept.get('name', 'Default')} Team",
                        "roles": _DEFAULT_ROLES[:3],
                    }
                ]

            departments.append(dept_def)
    elif extracted.teams:
        # No departments but teams exist — group under a default department
        departments.append(
            {
                "name": "Operations",
                "teams": [
                    {
                        "name": t.get("name", "Unknown Team"),
                        "roles": _infer_roles(t),
                    }
                    for t in extracted.teams
                ],
            }
        )

    return departments


def _build_root_envelope(extracted: ExtractedData) -> dict[str, Any]:
    """Build the root constraint envelope from extracted constraints."""
    envelope: dict[str, Any] = {}

    # Financial
    if extracted.financial_constraints:
        max_spend = _extract_max_value(extracted.financial_constraints)
        envelope["financial"] = {
            "max_spend_usd": max_spend,
            "requires_approval_above": max_spend * 0.5 if max_spend else None,
        }
    else:
        envelope["financial"] = {
            "max_spend_usd": None,
            "note": "Not yet defined — assessment gap",
        }

    # Operational
    if extracted.operational_constraints:
        envelope["operational"] = {
            "allowed_actions": _extract_list_values(
                extracted.operational_constraints, "allowed"
            ),
            "blocked_actions": _extract_list_values(
                extracted.operational_constraints, "blocked"
            ),
        }
    else:
        envelope["operational"] = {"note": "Not yet defined — assessment gap"}

    # Temporal
    if extracted.temporal_constraints:
        envelope["temporal"] = {
            "constraints": [str(c) for c in extracted.temporal_constraints],
        }
    else:
        envelope["temporal"] = {"business_hours_only": True}

    # Data access
    if extracted.data_access_constraints:
        envelope["data_access"] = {
            "default_clearance": "RESTRICTED",
            "policies": [str(c) for c in extracted.data_access_constraints],
        }
    else:
        envelope["data_access"] = {
            "default_clearance": "RESTRICTED",
            "note": "Not yet defined — assessment gap",
        }

    # Communication
    if extracted.communication_constraints:
        envelope["communication"] = {
            "policies": [str(c) for c in extracted.communication_constraints],
        }
    else:
        envelope["communication"] = {
            "external_allowed": False,
            "note": "Not yet defined — assessment gap",
        }

    return envelope


def _build_bridges(extracted: ExtractedData) -> list[dict[str, Any]]:
    """Build bridge definitions from extracted cross-team coordination data."""
    bridges: list[dict[str, Any]] = []
    for b in extracted.bridges:
        if isinstance(b, dict):
            bridges.append(
                {
                    "type": b.get("type", "standing"),
                    "teams": b.get("teams", []),
                    "purpose": b.get("purpose", ""),
                }
            )
        else:
            bridges.append(
                {
                    "type": "standing",
                    "description": str(b),
                }
            )
    return bridges


def _map_trust_posture(posture: str | None) -> str:
    """Map user-described trust posture to PACT posture identifier."""
    if not posture:
        return "supervised"
    lower = posture.lower()
    for key, value in _TRUST_POSTURE_MAP.items():
        if key and key in lower:
            return value
    return "supervised"


def _slugify(text: str) -> str:
    """Convert text to a URL-friendly slug."""
    return text.lower().replace(" ", "-").replace("_", "-")[:50]


def _infer_roles(team: dict[str, Any]) -> list[str]:
    """Infer appropriate roles for a team based on its name/description."""
    name = team.get("name", "").lower()
    if any(w in name for w in ["engineer", "dev", "tech"]):
        return ["data_analyst", "researcher"]
    if any(w in name for w in ["marketing", "content", "comm"]):
        return ["content_writer", "researcher"]
    if any(w in name for w in ["support", "customer", "service"]):
        return ["customer_support", "scheduler"]
    if any(w in name for w in ["exec", "leadership", "manage"]):
        return ["executive_assistant", "scheduler"]
    if any(w in name for w in ["research", "data", "analytics"]):
        return ["data_analyst", "researcher"]
    return _DEFAULT_ROLES[:2]


def _extract_max_value(constraints: list[dict[str, Any]]) -> float | None:
    """Try to extract a maximum monetary value from constraint descriptions."""
    for c in constraints:
        text = str(c).lower()
        for marker in ["$", "usd", "budget"]:
            if marker in text:
                import re

                numbers = re.findall(r"[\d,]+\.?\d*", text)
                if numbers:
                    return float(numbers[-1].replace(",", ""))
    return None


def _extract_list_values(constraints: list[dict[str, Any]], keyword: str) -> list[str]:
    """Extract list items from constraints matching a keyword."""
    results: list[str] = []
    for c in constraints:
        text = str(c).lower()
        if keyword in text:
            results.append(str(c))
    return results


def _build_summary(extracted: ExtractedData, config: dict[str, Any]) -> str:
    """Build a plain-language summary of the generated configuration."""
    org = extracted.org_name or "your organization"
    dept_count = len(config.get("departments", []))
    bridge_count = len(config.get("bridges", []))
    gap_count = len(config.get("_assessment_gaps", []))
    posture = config.get("organization", {}).get("initial_posture", "supervised")

    posture_descriptions = {
        "pseudo": "AI shadow mode — observing only, not taking actions",
        "supervised": "closely supervised — every action requires human approval",
        "shared_planning": "collaborative — AI proposes, humans approve key decisions",
        "continuous_insight": "mostly independent — AI acts, humans monitor patterns",
        "delegated": "fully autonomous — AI operates within defined boundaries",
    }
    posture_desc = posture_descriptions.get(posture, posture)

    parts = [
        f"Your PACT governance configuration for {org} is ready.",
        "",
        f"It defines {dept_count} department(s) with their teams and roles, "
        f"starting with a trust posture of '{posture_desc}'.",
    ]

    if bridge_count:
        parts.append(
            f"It includes {bridge_count} cross-team coordination bridge(s) "
            "to keep teams aligned."
        )

    if gap_count:
        parts.append(
            f"\nThere are {gap_count} area(s) where we didn't have enough information. "
            "These are marked in the configuration as gaps — your technical team "
            "can fill them in when they import this into your governance platform."
        )

    parts.extend(
        [
            "",
            "Your technical team can import this configuration file into the "
            "PACT governance platform to start enforcing these rules. "
            "You can download it using the button below.",
        ]
    )

    return "\n".join(parts)
